# .github/workflows/azure-static-web-apps.yml
name: Azure Static Web Apps (Blazor WASM)

on:
  push:
    branches: [ master ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ master ]

jobs:
  build_and_deploy:
    if: github.event_name != 'pull_request' || github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build & Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_DUNE_0B24A060F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: src/TypingGame.Wasm
          output_location: wwwroot

  close_pr_environment:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_DUNE_0B24A060F }}
          action: close
